spring.application.name=Peces a tierra


spring.datasource.url = jdbc:postgresql://localhost:5432/peces-a-tierra-test
spring.datasource.username = postgres
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update

spring.h2.console.enabled=true

jwt.secret=oZPh0e5IAAYRGdyE0oJoQfzA6C8k5AykmopwL4g6ZxrOSL6JoW5SlD381TG320b67osa5tS5h0YXOeTuTw0vwt5Ln36Tu9TUCPUBTqmlCj1xq50HcibUecUwnts7cuhn18hJCyEOEH0nJEgE

