spring.application.name=Peces a tierra


spring.datasource.url = jdbc:postgresql://localhost:5432/peces-a-tierra-test
spring.datasource.username = postgres
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update

spring.h2.console.enabled=true
